name: tidy

on:
  push:
  pull_request:

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: |
          sudo apt-get install -y clang clang-tidy clang-format bear make

      - name: create compile_commands.json
        run: |
          bear -- make -Bj

      - name: lint
        run: |
          find src -type f | xargs clang-tidy --warnings-as-errors=*

      - name: check formatting
        run: |
          find src -type f | xargs clang-format -Werror --dry-run

